### ISSUE TITLE
Support for raw flags in jobs

### ISSUE THREAD

**Issue by ledif** [ledif/dimebox#37]
There should be a way to write in the expfile flags that should be either added to the top of the job file or to the mpirun command. It is not possible for dimebox to capture every single use case for every system, so there should be a way to bypass the structured nature of the generation process and inject custom flags.

For example, if the user wanted to add the directive `#PBS -l mppnppn=12` to the top of every job, this could be expressed as the following in the expfile:

```yml
raw:
  headers: ['-l mppnppn=12']
```

This would require the machine config to specify that the prefix for headers on that system is `#PBS`.

In addition, to specify custom flags for the mpirun, such as `aprun -S 1`, this could be written in the expfile as

```yml
raw:
  runFlags: ['-S 1']
```

**Comment by timmiesmith** [comment]
I think the issue is more complex.  For example, running a scaling study where you wanted the nodes to be as lightly loaded as possible while increasing the process count would require the value of mppnppn to change.  In this example I would want to compute mppnppn as  the number of processes divided by the maximum number of nodes I can access.

The same for the -S option.  If the goal is to spread out the processes across the NUMA regions as much as possible the value passed to -S increases along with process count.

**Comment by ledif** [comment]
I believe this can be accomplished by still taking the same approach, but using the strings as [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals). This way, we can allow these flags to use information available to the current job's parameters.

For example, if would like `mppnppn` to be 12 for values of p > 12 and p when p <= 12, we could write something like:

```yml
raw:
  headers: ['-l mppnppn=${p>12 ? 12 : p}']
```

**Comment by timmiesmith** [comment]
With the template literals included I think that the flag specification in the expfile would provide the desired support.
